# Generated by Django 4.1.3 on 2022-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_employee_alter_car_cartype_alter_car_image_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterField(
            model_name='treatment',
            name='type',
            field=models.IntegerField(choices=[(1, '10,000 Treatment'), (2, 'BREAKS'), (3, '30,000 Treatment')]),
        ),
    ]
